version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: parkpal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
