import { ParkingSpot, Booking, PaymentMethod } from '../types';

export const mockParkingSpots: ParkingSpot[] = [
  {
    id: '1',
    title: 'Downtown Parking Garage',
    address: '123 Main St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    latitude: 37.7749,
    longitude: -122.4194,
    price: 8,
    priceUnit: 'hour',
    rating: 4.5,
    reviews: 128,
    distance: 0.5,
    availability: 'available',
    images: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    amenities: ['Security', 'Covered', 'EV Charging', 'CCTV'],
    description:
      'Secure covered parking in the heart of downtown. Perfect for daily commuters with 24/7 access.',
    ownerId: 'owner1',
    ownerName: 'John Smith',
    ownerRating: 4.8,
    features: {
      covered: true,
      security: true,
      evCharging: true,
      accessible: true,
      lighting: true,
      cctv: true,
    },
  },
  {
    id: '2',
    title: 'Mission Bay Parking',
    address: '456 Bay St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94158',
    latitude: 37.7706,
    longitude: -122.3782,
    price: 6,
    priceUnit: 'hour',
    rating: 4.2,
    reviews: 89,
    distance: 1.2,
    availability: 'available',
    images: [
      'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800',
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800',
    ],
    amenities: ['Security', 'Accessible', 'Lighting'],
    description:
      'Outdoor parking lot near the bay area with easy access to public transport.',
    ownerId: 'owner2',
    ownerName: 'Sarah Johnson',
    ownerRating: 4.5,
    features: {
      covered: false,
      security: true,
      evCharging: false,
      accessible: true,
      lighting: true,
      cctv: false,
    },
  },
  {
    id: '3',
    title: 'Financial District Spot',
    address: '789 Market St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94103',
    latitude: 37.7879,
    longitude: -122.4074,
    price: 12,
    priceUnit: 'hour',
    rating: 4.7,
    reviews: 203,
    distance: 0.3,
    availability: 'available',
    images: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
    ],
    amenities: ['Security', 'Covered', 'EV Charging', 'CCTV', 'Valet'],
    description:
      'Premium covered parking in the financial district with valet service available.',
    ownerId: 'owner3',
    ownerName: 'Michael Chen',
    ownerRating: 4.9,
    features: {
      covered: true,
      security: true,
      evCharging: true,
      accessible: true,
      lighting: true,
      cctv: true,
    },
  },
  {
    id: '4',
    title: 'SoMa Parking Lot',
    address: '321 Folsom St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94107',
    latitude: 37.7857,
    longitude: -122.3933,
    price: 5,
    priceUnit: 'hour',
    rating: 3.9,
    reviews: 54,
    distance: 0.8,
    availability: 'available',
    images: [
      'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800',
    ],
    amenities: ['Accessible', 'Lighting'],
    description: 'Affordable outdoor parking in SoMa district.',
    ownerId: 'owner4',
    ownerName: 'Emily Davis',
    ownerRating: 4.1,
    features: {
      covered: false,
      security: false,
      evCharging: false,
      accessible: true,
      lighting: true,
      cctv: false,
    },
  },
  {
    id: '5',
    title: 'Union Square Garage',
    address: '555 Post St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    latitude: 37.7880,
    longitude: -122.4074,
    price: 10,
    priceUnit: 'hour',
    rating: 4.6,
    reviews: 167,
    distance: 0.4,
    availability: 'occupied',
    images: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800',
    ],
    amenities: ['Security', 'Covered', 'CCTV', 'Accessible'],
    description:
      'Convenient parking near Union Square shopping district with 24/7 security.',
    ownerId: 'owner5',
    ownerName: 'David Martinez',
    ownerRating: 4.7,
    features: {
      covered: true,
      security: true,
      evCharging: false,
      accessible: true,
      lighting: true,
      cctv: true,
    },
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    spotId: '1',
    spotTitle: 'Downtown Parking Garage',
    spotAddress: '123 Main St, San Francisco',
    spotImage: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
    userId: '1',
    startDate: new Date(Date.now() + 86400000).toISOString(),
    endDate: new Date(Date.now() + 90000000).toISOString(),
    duration: 1,
    price: 8,
    status: 'upcoming',
    paymentMethod: 'Visa ****1234',
    qrCode: 'QR-12345',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    spotId: '2',
    spotTitle: 'Mission Bay Parking',
    spotAddress: '456 Bay St, San Francisco',
    spotImage: 'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800',
    userId: '1',
    startDate: new Date(Date.now() - 3600000).toISOString(),
    endDate: new Date(Date.now() + 3600000).toISOString(),
    duration: 2,
    price: 12,
    status: 'active',
    paymentMethod: 'Mastercard ****5678',
    qrCode: 'QR-12346',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '3',
    spotId: '3',
    spotTitle: 'Financial District Spot',
    spotAddress: '789 Market St, San Francisco',
    spotImage: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
    userId: '1',
    startDate: new Date(Date.now() - 172800000).toISOString(),
    endDate: new Date(Date.now() - 169200000).toISOString(),
    duration: 1,
    price: 12,
    status: 'completed',
    paymentMethod: 'Visa ****1234',
    qrCode: 'QR-12347',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: '1',
    type: 'card',
    label: 'Visa',
    details: '****1234',
    isDefault: true,
  },
  {
    id: '2',
    type: 'card',
    label: 'Mastercard',
    details: '****5678',
    isDefault: false,
  },
  {
    id: '3',
    type: 'paypal',
    label: 'PayPal',
    details: 'user@example.com',
    isDefault: false,
  },
];
